---
prometheus.enabled: true
prometheus.port: 8080
exampletemplateservice.port: 5000
exampletemplateservice.hostName: 0.0.0.0
exampletemplateservice.logFile: null
exampletemplateservice.logLevel: info
fastapi.logLevel: warning


storage.serviceName: image_detection_service   #<your-service-name>
models.enabledTypes:
        - yolo

yolo.modelName: yolov4.weights

yolo.weightPath: '/etc/image_detection_service/models/yolo/yolov4.weights' #/etc/<your-service-name/models/yolo/yolov4.weights
yolo.finalweights: '/etc/image_detection_service/models/yolo_checkpoint'   #/etc/<your-service-name/models/yolo_checkpoint
yolo.tiny: False
yolo.input_size: 416
yolo.framework: tf
yolo.model: yolov4
yolo.iou: 0.45
yolo.score_threshold: 0.50

#Bucket name in your google strogae [#If you are hosting your models in GoogleStorage Make sure to make the bucket public where you host your model]
storage.bucket: md-data-bingemarkers

#If you are hosting your models in DropBox then make sure to use your own access token that you can set up from DROPBOX.
#This one most probably won't work. [If you Don't have a dropbox you can contact me and I can generate a new token for you to run the service.]
dropbox.accesstoken: 'sl.BRgbNg8DSLorFWLbRMB_g9uInOq8FwhFZnZiqc_vQ60yWAyhiNAK8oDyFB5XTL8Pnz5x4xOUZMQLBQ5eMBo9-kr-klgLOMoV60UMrJKCj-h0Dwx5RRcmSbuWEZLh6Q-3pZ7E2FJ4syp4'
dropbox.dropbox_file_path: '/Apps/Yolo4_demo_test/yolov4.weights'
